const cfg = window.BOHOL_WHALE_SHARK_CONFIG;
const params = new URLSearchParams(location.search);
const pkg = cfg.packages.find(p => p.slug === params.get('package')) || cfg.packages[0];
const pickup = params.get('pickup') || 'To be confirmed';
const date = params.get('date') || 'To be confirmed';
const guests = params.get('guests') || '2';
const money = typeof pkg.price === 'number' ? new Intl.NumberFormat('en-PH',{style:'currency',currency:cfg.currency,maximumFractionDigits:0}).format(pkg.price) : cfg.priceStatus;
document.querySelector('#sumPackage').textContent = pkg.name;
document.querySelector('#sumPickup').textContent = pickup;
document.querySelector('#sumDate').textContent = date;
document.querySelector('#sumGuests').textContent = guests;
document.querySelector('#sumPrice').textContent = money;
document.querySelector('.menu-btn')?.addEventListener('click',()=>document.querySelector('.nav-links').classList.toggle('open'));
document.querySelector('#reservationForm').addEventListener('submit', e=>{
  e.preventDefault();
  const box=document.querySelector('#formMessage');
  box.hidden=false;
  box.innerHTML='<strong>Booking framework is working.</strong><p class="small">Next step after rates are finalized: connect this form to your reservation database and PayMongo Cloudflare Worker.</p>';
  box.scrollIntoView({behavior:'smooth',block:'center'});
});
